version: '3.7'

services:
  app:
    network_mode: host
    build: 
      context: .
    volumes:
      - ./JobOffersSite:/app
      - ./media:/vol/web
    command: sh -c "python manage.py runserver"
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
