# Generated by Django 3.2.9 on 2021-11-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('mail', models.CharField(max_length=50)),
                ('official_site', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('finish_date', models.DateTimeField(verbose_name='date offer ends')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobOffers.company')),
            ],
        ),
    ]
